hub:
  image: selenium/hub
  ports: 
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  links:
    - hub
#  firefox-custom:
#    build: ./firefox
#    links:
#      - hub
#    environment:
#      - FIREFOX_VERSION=nightly-latest
chrome:
  image: selenium/node-chrome
  links:
    - hub
chrome-debug:
  image: selenium/node-chrome-debug
  links:
    - hub
front:
  build: ./front-test
  ports:
    - "8080:80"
